/** Master `document.code` values for system print templates (seeded). */
export const DOCUMENT_PRINT_CODE = {
	NURSING_COMPLETE: 'NURSING_COMPLETE_PRINT',
	OP_BILL: 'OP_BILL_PRINT',
	VISIT_LABEL: 'VISIT_LABEL_PRINT',
	APPOINTMENT_SLIP: 'APPOINTMENT_SLIP_PRINT',
	MED_ORDER_RECEIPT: 'MED_ORDER_RECEIPT_PRINT'
} as const;

export type DocumentPrintCode =
	(typeof DOCUMENT_PRINT_CODE)[keyof typeof DOCUMENT_PRINT_CODE];

/** @deprecated Use DOCUMENT_PRINT_CODE.NURSING_COMPLETE */
export const EMR_NURSING_COMPLETE_PRINT_DOCUMENT_CODE =
	DOCUMENT_PRINT_CODE.NURSING_COMPLETE;
